server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://127.0.0.1:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
